apiVersion: v1
kind: Pod
metadata: 
  name: labelpod
  labels:
    env: dev
spec:
  containers:
    - name: labelcontainer
      image: nginx
      ports: 
        - containerPort: 80
          protocol: TCP