apiVersion: v1
kind: Pod
metadata:
  name: maincontainerpod
spec:
  containers:
    - name: maincontainer
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
          