apiVersion: v1
kind: Pod
metadata:
  name: sqlpod
spec:
  containers:
    - name: sqlcontainer
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: kishoretable
        - name: MYSQL_USER
          value: kishore
        - name: MYSQL_PASSWORD
          value: kishore123
          ports: 
            - containerPort: 3306
              protocol: TCP